### ISSUE TITLE
[FE] Feat: 카테고리 선택 컴포넌트 작성

### ISSUE THREAD

**Issue by leewooseong** [ggumms/ggumtle#11]
## 🚧 Description
회원 가입 및 버킷 생성에 사용되는 카테고리 선택 컴포넌트와 카테고리 분류를 나타내주는 컴포넌트를 작성합니다.

## ✅ Todo
- [x] Tailwind config에서 컬러 변경 적용하기
- [x] 카테고리 팔레트 만들기
- [x] 데이터 선택 시 state로 선택된 데이터 관리

### Tailwind 배경색 설정하기
- 변수를 이용해서 color를 넣게되면 반영이 안되는 문제를 발견
- 동적 클레스의 경우 selfList를 이용하거나, 별도의 클래스 리스트를 만들어서 관리해줄 수 있다.
- 아래 블로그에서 동적으로 클래스를 사용하는 다양한 방법에 대해 알려주고 있다.
- https://moon-ga.github.io/tailwind_css/2-dynamic-classnames/
- https://github.com/ggumms/ggumtle/issues/11#issue-2089855908

### State의 자료구조 정하기
- category처럼 다양한 종류의 버튼을 선택하는 경우 선택된 데이터 관리가 필요하다.
- 처음에는 배열을 이용해서 선택된 category의 이름을 관리했다. -> 이렇게 하면 선택 여부 검색에 O(n), 선택 정보 관리에 O(1) 
- 지금은 객체를 이용해서 데이터의 선택여부를 판단한다. -> 이렇게 하면 선택 여부 검색에 O(1), 선택 정보 관리에 O(1) 
-> 하지만 지금 방식이 최적이 아닐 것 같아서 추후 어떤 식으로 개발하는게 맞는지 생각해볼 필요가 있다.
-> useMemo 사용해서 최적화  할 수 있는 방법 고민해보기([]로 state를 관리하는 케이스)
