### ISSUE TITLE
[FE] Feat: 팔로우/팔로잉 상세 페이지

### ISSUE THREAD

**Issue by 3o14** [ggumms/ggumtle#131]
## 🚧 Description
사용자 프로필에서 팔로우/팔로잉 버튼을 클릭하면 상세 페이지로 이동한다.

## ✅ Todo
- [x] 페이지 레이아웃 제작
- [x] 클릭시 사용자 상세 페이지로 이동
- [x] 팔로우/팔로잉 버튼 클릭시 팔로우/팔로우취소 가능
