### ISSUE TITLE
[BE] Fix: 테스트 및 잔잔바리 수정

### ISSUE THREAD

**Issue by DarkBlackRice** [ggumms/ggumtle#135]
## 🚧 Description

테스트 진행하고 변경 사항 반영하는 이슈입니다
테스트가 끝나면 닫겠습니다
지속적으로 수정됩니다

## ✅ Todo
- [x] UpdateBucketRequestDto timeCapsule 필드 삭제
- [x] BucketController Swagger 오타 수정
- [x] PostBucketReactionRequestDto @Scheme 추가
- [x] 컨트롤러 순서 수정
- [x] 유사한 Dto 필드명 수정
