### ISSUE TITLE
[BE] Feat: 유저 기능 구현

### ISSUE THREAD

**Issue by 404-not-foundl** [ggumms/ggumtle#16]
## 🚧 Description

유저 기능 구현

## ✅ Todo
- [x] 유저 수정
- [x] 유저 정보 검색 - 유저 정보, 유저 + 달성도 팔로워 팔로잉 정보
- [x] 유저 팔로워, 팔로잉 리스트
- [x] 유저 팔로우, 언팔로우 - isFollowing
- [x] 유저 검색
- [x] 대표버킷 UD
- [x] 유저 더미 4개 추가
- [x] 유저 테스트
