### ISSUE TITLE
[FE] Feat: 버킷 달설 페이지 꿈틀 컴포넌트 + 버튼 제작

### ISSUE THREAD

**Issue by leewooseong** [ggumms/ggumtle#160]
## 🚧 Description
버킷 달성 페이지에서 사용되는 꿈틀 컴포넌트 및 버튼을 개발하고 게이지 효과를 넣어줍니다.

## ✅ Todo
- [ ] 꿈틀 컴포넌트 적용
- [ ] 달성 버튼 구현
- [ ] 달성 버튼 및 꿈틀 컴포넌트 애니메이션 연동
