### ISSUE TITLE
[FE] Fix: 검색시 마지막 입력값 안들감 에러 수정 및 마무으리

### ISSUE THREAD

**Issue by 3o14** [ggumms/ggumtle#221]
## 🚧 Description
마무으리를 해봅시당 현재시각 4시 29분 히히

## ✅ Todo
- [x] 헤더 상단 고정
- [x] 검색 페이지 검색바 상단 고정
- [ ] 검색시 입력 에러 수정
- [ ] 알림페이지 읽음 한번에 처리 에러 수정
- [ ] 폰트 볼드체 적용시키기
