### ISSUE TITLE
[FE] Feat: 지도를 이용해서 위치 정보 입력 컴포넌트 작성

### ISSUE THREAD

**Issue by leewooseong** [ggumms/ggumtle#25]
## 🚧 Description
지도 api를 이용하여 버킷 작성 페이지에서 사용되는 버킷 관련 위치 정보를 받아오고 state를 설정해주는 컴포넌트 작성

## ✅ Todo
- [ ] 지도 api를 이용하여 위치 정보 받아오는 방법 찾아보기
- [ ] 주소지 입력을 통해 위치 정보를 받아오는 방법 알아보기
- [ ] 찾아본 방법을 이용하여 위치 정보 받아오는 페이지 구현
- [ ]  kakao map api 연동
- [ ] 위치 정보 선택 컴포넌트 개발
- [ ] 전체 페이지 UI 작성
- [ ] zustand를 이용해서 bucket 정보에 해당하는 store에 페이지별 state를 slice로 관리하면서 개발 진행하기
- [ ] 다음 버튼 작성시 활성화 상태를 기본으로 넘겨주기
