### ISSUE TITLE
[FE] Feat: 버킷리스트 작성페이지 구현

### ISSUE THREAD

**Issue by leewooseong** [ggumms/ggumtle#28]
## 🚧 Description
사전 이슈 수행을 통해 만들어진 컴포넌트를 이용해서 버킷리스트 작성페이지를 구현한다.

## ✅ Todo
- [x] 버킷리스트 카테고리 선택 페이지 구현
- [x] 버킷리스트 색상, 제목, 타입캡슐 페이지 구현
- [ ] 리마인드 위치 지정 페이지 구현(옵션 정보)
- [x] 이미지, 버킷 시작일, 리마인드 주기, 공개 여부 설정 페이지 구현
- [ ] 이전 페이지(카테고리 선택)의 입력이 없는데 이후 페이지(위치 지정 페이지)로 이동하려고 한다고 이전 페이지로 이동시키기
- [ ] 페이지 나갈 때 저장되지 않은 데이터가 삭제된다는 메세지 표시하기
- [ ] React-Query를 이용하여 페이지 api 연동
