### ISSUE TITLE
[BE] Fix: 시큐리티 설정 오류 수정 및 User 테이블 스키마 추가

### ISSUE THREAD

**Issue by 404-not-foundl** [ggumms/ggumtle#30]
## 🚧 Description

시큐리티 설정 오류 수정 및 User 테이블 스키마 추가

## ✅ Todo
- [x] Spring Security 설정 오류 해결
- [x] resources에 data-mysql.sql 및 schema-mysql.sql에 User 테이블과 예시 데이터 추가
- [x] 개발 토큰을 위한 User 테이블에 관련 데이터 추가
