### ISSUE TITLE
[FE] Setting: 프로젝트 라우터, Tailwind 추가 설정 및 리액트 아이콘 설치

### ISSUE THREAD

**Issue by leewooseong** [ggumms/ggumtle#34]
## ✅ Todo
- [x] DefaultLayout 적용
- [x] Router 협의 후 설정 변경
- [x] 404 Page 설정
- [x] Tailwind 추가 설정
- [x] 리액트 아이콘 설치
