### ISSUE TITLE
[INFRA] Setting : 서버 구축

### ISSUE THREAD

**Issue by hoing97s** [ggumms/ggumtle#6]
## 🚧 Description

EC2 서버 구축 

## ✅ Todo
- [x] DB 설치 및 연동
- [x] 도커 설치 및 레지스트리 구축
- [x] 젠킨스 설치 및 연동
- [x] 배포 스크립트 작성
