### ISSUE TITLE
[FE] Feat: 카테고리 선택 페이지 개발

### ISSUE THREAD

**Issue by leewooseong** [ggumms/ggumtle#60]
## 🚧 Description
버킷리스트에서 카테고리를 선택하는 페이지 개발 

## ✅ Todo
- [x] 헤더 및 설명 문구 컴포넌트 개발
- [x] 다른 페이지로 넘어가는 버튼 컴포넌트 작성하기
- [x] 재사용 컴포넌트들 사용해서 UI 개발하기
- [x] 1개 이상 선택했을 경우 버튼 활성화 되도록 처리
