### ISSUE TITLE
[FE] Feat: 버킷리스트 작성_꿈내용 페이지 개발

### ISSUE THREAD

**Issue by leewooseong** [ggumms/ggumtle#63]
## 🚧 Description
버킷리스트 작성 페이지 중에서 꿈 내용 페이지에 해당하는 페이지 개발 

## ✅ Todo
- [x] category에서 선택한 색상 반영하여 꿈:틀 색상 정하는 컴포넌트 개발
- [x] 제목 및 타입캡슐 작성 컴포넌트 개발
- [x] 전체 페이지 UI 작성
- [x] zustand를 이용해서 bucket 정보에 해당하는 store에 페이지별 state를 slice로 관리하면서 개발 진행하기
- [x] 다음 버튼 추가

## 🛠️삽질로그
- declare type
