### ISSUE TITLE
[BE] Feat: 친밀도 로직 구현

### ISSUE THREAD

**Issue by jjjoina** [ggumms/ggumtle#67]
## 🚧 Description

사용자가 행하는 활동에 따라 친밀도를 반영합니다.

## ✅ Todo
- [x] (보류) 팔로이와 내가 공통적으로 가지고 있는 interest에 따른 친밀도 산정
- [x] 팔로이의 버킷을 조회한 경우
- [x] 팔로이의 후기를 조회한 경우
- [x] 팔로이의 버킷에 리액션을 남긴 경우 + 취소한 경우
- [x] 팔로이의 후기에 리액션을 남긴 경우 + 취소한 경우
- [x] 팔로이의 버킷에 댓글을 남긴 경우 + 삭제한 경우
- [x] 팔로이의 후기에 댓글을 남긴 경우 + 삭제한 경우
- [x] 내 버킷에 있는 팔로이의 댓글에 좋아요를 누른 경우 + 취소한 경우
- [x] 내 후기에 있는 팔로이의 댓글에 좋아요를 누른 경우 + 취소한 경우
- [x] (보류) 팔로잉하지 않은 상태에서 위의 행위들을 했을 경우
- [x] 친밀도는 0보다 낮아지지 않는다.
