### ISSUE TITLE
[FE] Feat: 버킷리스트 작성_추가 정보 페이지 개발

### ISSUE THREAD

**Issue by leewooseong** [ggumms/ggumtle#69]
## 🚧 Description
버킷리스트 작성 페이지 중에서 추가 정보 페이지에 해당하는 페이지 개발

## ✅ Todo
- [x] 이미지 추가 컴포넌트 개발
- [x] 버킷 시작일 컴포넌트 개발 (라이브러리 사용)
- [x] 리마인드 주기 컴포넌트 개발
- [x] 공개 여부 컴포넌트 개발(Material UI 적용)
- [x] 작성 완료 버튼 컴포넌트 개발 
- [x] 전체 UI 작성
- [ ] tailwind.config.js 수정해서 달력 및 드롭다운 스타일 다시 맞추기
- [ ] 이전 state가 비었을 경우 그 페이지로 이동시키는 작업 수행
- [ ] post api연동
- [ ] put api 연동

### 이미지 undefined 문제
- 이미지 선택 -> 이미지 재선택 후 취소 버튼을 누를 시 현재 input[type='file']의 값이 undefiend로 출력되는 문제 파악 
- 서버로 보낼 정보 및 화면에 보여줘야 하는 정보를 state로 관리하여 문제 해결 
- https://velog.io/@kwonja/input-file-undefined-%EB%AC%B8%EC%A0%9C

### 프론트에서 image 띄워주기
- 화면에 이미지를 띄우는 것은 프론트에서 처리해야 된다는 점을 파악
- FileReader 및 FileReader의 onload 이벤트 메서드를 이용해 문제 해결
- https://developer.mozilla.org/ko/docs/Web/API/FileReader

### Dropdown & Modal dot notation
- 리마인더 주기와 버킷 시작일을 생성하면서 컴포넌트 재사용성에 대한 사례 적용 시도
- dot notation을 적용하기 전에 HeaderLess UI를 적용해서 유사 개념 적용해보기
- 
- https://www.youtube.com/watch?v=fR8tsJ2r7Eg
