### ISSUE TITLE
[FE] Feat: 사용자 페이지 컴포넌트 제작

### ISSUE THREAD

**Issue by 3o14** [ggumms/ggumtle#70]
## 🚧 Description
사용자 페이지에서 사용할 컴포넌트를 제작합니다.

## ✅ Todo
- [x] 달성률, 팔로워, 팔로잉 컴포넌트 제작
- [x] 사용자 페이지 프로필 컴포넌트 제작
- [x] 피드용 컴포넌트 제작
- [x] 팔로워/팔로잉 하나의 컴포넌트 제작

#### 버튼 클릭시 색상 자연스럽게 변경시키기
* tailwind class `transition-colors`
* https://tailwindcss.com/docs/transition-property

#### 피그마 벡터 svg로 추출하기
* 참고 블로그: https://velog.io/@rachelyu1025/Figma로-svg-추출하여-react-컴포넌트로-사용하기
* svg 코드 변환 사이트: https://jakearchibald.github.io/svgomg/
* width, height 설정시 잘리지 않게 하려면 `viewBox` 설정을 해줘야 함
* `viewBox="0 0 {원본 width} {원본 height}"`
```tsx
export const CoolReaction = () => {
	return (
		<div>
                       // viewBox
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 103 102" width="40" height="40" fill="none">
				<path ... />
			</svg>
		</div>
	)
}
```
