### ISSUE TITLE
[FE] Feat: 레이다 팔로잉탭 미리보기 및 페이지 전환

### ISSUE THREAD

**Issue by 3o14** [ggumms/ggumtle#71]
## 🚧 Description
레이다 팔로잉탭에서 유저를 클릭하면 미리보기가 뜨고,
새로고침을 클릭하면 새로고침이 됩니다.
미리보기가 뜬 유저 정보를 위로 끌어올리면 사용자 페이지로 전환됩니다.

## ✅ Todo
- [x] 유저 미리보기 컴포넌트 제작
- [x] 새로고침 기능 구현
- [x] 유저 클릭시 미리보기
- [x] 페이지 전환 모션 구현
