### ISSUE TITLE
[FE] Feat: 레이더 전체탭 미리보기 및 카테고리 선택 기능

### ISSUE THREAD

**Issue by 3o14** [ggumms/ggumtle#72]
## 🚧 Description
레이더 전체탭 페이지에서 버킷을 클릭하면 버킷 미리보기가 뜹니다.
아래 drawer를 클릭 혹은 밀어올리면 카테고리 선택을 할 수 있습니다.
버킷이 미리보기가 뜨는 경우는 레이더 위의 버킷을 클릭했을 때 뿐입니다.

## ✅ Todo
- [x] 버킷 미리보기 컴포넌트 제작
- [x] 카테고리 선택 기능 구현
- [ ] 버킷 미리보기를 끌어올리면 버킷 상세 페이지로 이동
