### ISSUE TITLE
[FE] Feat: 검색하기 레이아웃 구현

### ISSUE THREAD

**Issue by 3o14** [ggumms/ggumtle#74]
## 🚧 Description
레이더 위 고정된 돋보기 아이콘을 누르면 검색하기 페이지로 이동합니다.
검색하기 페이지는 후기, 꿈틀, 사용자 순으로 세가지 탭으로 이루어져 있습니다.

## ✅ Todo
- [x] 돋보기 버튼 구현
- [x] 클릭시 검색 페이지로 이동
- [x] 삼탭 레이아웃 구현
