### ISSUE TITLE
[FE] Feat: 버킷리스트 작성 페이지 레이아웃 구현

### ISSUE THREAD

**Issue by leewooseong** [ggumms/ggumtle#8]
## 🚧 Description
버킷리스트 작성, 회원가입 및 레이다 화면에 사용되는 작성 

## ✅ Todo
- [x] 버킷리스트 작성 페이지 레이아웃 UI 구현
- [x] 버튼 클릭할 경우 하위 페이지 변경 기능 구현
- [x] 버튼 클릭에 따른 애니메이션 적용(framer-motion 라이브러리 적용)
- [x] bucket/write페이지로 접근했을 경우 처리
- [x] routerData 이용해서 headerData 생성하기

### 1. framer motion 적용 시..
처음에는 data-attribute + onClick 핸들러 함수로 구현 시도
  ➡️  페이지 리로드 시에 초기 index를 제대로 못잡거나 빈값으로 할당되어 버리는 문제가 생긴다.
    1. useState의 초기값을 빈 값으로 두면 초기값이 빈값으로 할당
    2. useState의 초기값이 빈 값이 아니면 초기 값이 해당 값으로 할당

➡️ 둘 다 현재 페이지 정보와 무관한 값으로 할당되는 케이스가 있어 구현은 `currentPath`를 이용한 방법으로 전환

- https://velog.io/@minu_624/TIL-React-DropDown
