### ISSUE TITLE
[BE] Style: 버킷 코드 스타일 수정

### ISSUE THREAD

**Issue by DarkBlackRice** [ggumms/ggumtle#80]
## 🚧 Description
API 명세서 정리하며 발견한 내용들을 수정해봅시다

## ✅ Todo
- [x] 색상 오류 반환 메세지 수정
- [x] update DTO 타임캡슐 필드 삭제
- [x] 네이밍 컨벤션 통일
- [x] request DTO 사이즈 수정
