### ISSUE TITLE
[FE] Feat: 유저 프로필 공통 컴포넌트 제작

### ISSUE THREAD

**Issue by leewooseong** [ggumms/ggumtle#9]
## 🚧 Description
댓글, 프로필, 검색 페이지에서 사용될 공통 컴포넌트 제작

## ✅ Todo
- [x] props를 이용한 컴포넌트 재사용 관련 학습 수행
- [x] 유저 프로필 ui 제작
- [x] 유저 프로필 클릭했을 경우 해당 피드 페이지로 이동
- [x] 대표 버킷이 있다면 클릭했을 경우 해당 버킷 상세 페이지로 이동
- [x] 달성 여부에 따라서 버킷 ui 변경
- [x] tailwind 설정을 통해서 동적 클래스 사용하도록 변경

### Tailwind의 SafeList 활용하기
- 정규식을 이용해서 dynamicClass를 대신하여 css를 자동으로 생성해줄려고 했으나 처리가 되지 않습니다..
